version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: 'bugfix'
    pass:
      - do: labels
        add: ['bug']
